Applikation/flaskr/users/models.py
from datetime import datetime 
from flaskr import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))



class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username=db.Column(db.String(20), unique=True, nullable=False)
    email=db.Column(db.String(120), unique=True, nullable=False)
    image_file=db.Column(db.String(20), nullable=False, default='default.jpg')
    password=db.Column(db.String(60), nullable=False)
    posts=db.relationship('Post', backref='autor', lazy=True)
    topics=db.relationship('Topic', backref='autor', lazy=True)
    sheets=db.relationship('Sheet', backref='autor', lazy=True)
    


    def __repr__(self):
        return f"User ('{self.username}','{self.email}','{self.image_file}')"

        

Applikation/flaskr/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, IntegerField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flaskr.users.models import User

class RegistrationForm(FlaskForm):
    username= StringField('Nutzername', validators=[DataRequired(), Length(min=1, max=30)])
    email=StringField ('E-Mail-Adresse', validators=[DataRequired(), Email()]) 
    password=PasswordField('Passwort', validators=[DataRequired()])
    confirm_password=PasswordField('Passwort erneut eingeben', validators=[DataRequired(), EqualTo('password')])
    image_file = FileField('Profilbild', validators=[
        FileAllowed(['jpg', 'png'], 'Images only!')
    ])
    submit=SubmitField('Registrieren')

    def validate_username(self, username):
        user=User.query.filter_by(username=username.data).first()

        if user:
            raise ValidationError('Dieser Nutzername wurde schon verwendet')

    def validate_email(self, email):
        user=User.query.filter_by(email=email.data).first()

        if user:
            raise ValidationError('Diese E-Mail-Adresse wurde schon verwendet')


class LoginForm(FlaskForm):
    email=StringField ('E-Mail-Adresse', validators=[DataRequired(), Email()])
    password=PasswordField('Passwort', validators=[DataRequired()])
    remember=BooleanField('Remember Me')
    submit=SubmitField('Login')

class UpdateAccountForm(FlaskForm):
    password=PasswordField('Neues Passwort')
    confirm_password=PasswordField('Passwort erneut eingeben', validators=[EqualTo('password')])
    image_file = FileField('Neues Profilbild', validators=[
        FileAllowed(['jpg', 'png'], 'Images only!')
    ])
    submit=SubmitField('Speichern')



class TestForm(FlaskForm):
    testtext = StringField('Testtext', validators=[DataRequired()])
    testpicture = FileField('Test-Picture')
    submit=SubmitField('Testsubmit')

Applikation/flaskr/users/views.py
import os
import secrets
from PIL import Image
from flask import Blueprint, render_template, request, redirect, url_for, flash, abort
from flaskr import app, db, bcrypt 
from flaskr.users.forms import RegistrationForm, LoginForm, TestForm, UpdateAccountForm
from flaskr.users.models import User
from flask_login import login_user, current_user, logout_user, login_required


mod = Blueprint('users', __name__, url_prefix='/users')

@mod.route('/register/', methods=['GET', 'POST'] )
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home2'))

    form=RegistrationForm()
    if form.validate_on_submit():
            hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user=User(username=form.username.data, email=form.email.data, password=hashed_password) 
            if form.image_file.data:
                img_file= save_profile_pic(form.image_file.data)
                user.image_file=img_file
            else:
                user.image_file="default.png"
            db.session.add(user)
            db.session.commit()
            flash(f'Account wurde erstellt, Sie können sich einloggen', 'success')
            return redirect(url_for('users.login')) 


    return render_template('users/register.html', form=form)


@mod.route('/login/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home2'))

    form=LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page= request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('home2'))
        else:
            flash(f'Ckeck email and password!', 'danger') 

    return render_template('users/login.html', title='Login', form=form)

@mod.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('home'))

@mod.route('/view_users/')
def users():   
       users= User.query.all()
       return render_template('users/view_users.html', users=users)



def save_profile_pic(profile_pic):
    random_hex_code=secrets.token_hex(8)
    _, f_ext= os.path.splitext(profile_pic.filename)
    hex_picture_name= random_hex_code + f_ext
    picture_path=os.path.join(app.root_path, 'static/profile_pics', hex_picture_name)

    output_size=(60, 60)
    image= Image.open(profile_pic)
    image.thumbnail(output_size)
    image.save(picture_path)

    return hex_picture_name

@mod.route('/update_account', methods=['GET', 'POST'])
@login_required
def account():
    form=UpdateAccountForm()
    if form.validate_on_submit():
        if form.password.data:
            hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            current_user.password=hashed_password 
        if form.image_file.data:
            img_file= save_profile_pic(form.image_file.data)
            current_user.image_file=img_file
        else:
            current_user.image_file="default.png"
        db.session.commit()
        flash('Profil wurde angepasst', 'success')
        return redirect(url_for('home2'))
   

    image_file=url_for('static', filename='profile_pics/'+ current_user.image_file)
    return render_template('users/update_account.html', title='Account', image_file=image_file, form=form)

   

Applikation/flaskr/templates/users/login.html
{% extends 'base.html' %}

{%block head  %}
      <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
      {% endblock%}

{%block body %}
<br>
<h1>PrepPool</h1>
    <br>
<div class="content-section">
  <form method ="POST" action="">
  
      {{  form.hidden_tag()  }}
      <br>
     
      <fieldset class="form-group">
          <legend class="border-bottom mb-4"> Login: Bitte E-Mail-Adresse und Passwort eingeben. </legend>
  
          <br>
       <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {%if form.email.errors%}
           {{ form.email(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {%for error in form.email.errors%}
            <span> {{error}}</span>
            {%endfor%}
            </div>
          {%else%}
          {{form.email (class="form-control form-control-lg")}}
          {%endif%}

        </div>
        <br>
        <div class="form-group">
          {{ form.password.label(class="form-control-label") }}
          {%if form.password.errors%}
           {{ form.password(class="form-control form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {%for error in form.password.errors%}
            <span> {{error}}</span>
            {%endfor%}
            </div>
          {%else%}
          {{form.password (class="form-control form-control-lg")}}
          {%endif%}
        </div>
        <br>
        
        
      </fieldset>
      <br>
      <div class="form-group">
      {{form.submit(class="btn btn-outline-info") }}
      </div>
      <br>
      <!--<small class="text-muted ml-2">
                  <a href="#">Passwort vergessen?</a>
      </small>-->
  </form>
</div> 
<br>
<div class="border-top pt-3">

   <small class="text-muted">
      Noch kein Account?   <a class= "ml-2" href="{{ url_for('users.register')}}">Sign Up now</a>
   </small>
</div>

{% endblock body%}

Applikation/flaskr/templates/users/register.html
{% extends 'base.html' %}

{%block head  %}
      <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
      {% endblock%}

{% block body %}
<br>
<h1>PrepPool</h1>
    <br>
<div class="content-section">
    <form method="POST" enctype ="multipart/form-data" action="">
        {{ form.hidden_tag() }}

        <br>
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"> Registrieren Sie sich </legend>

            <div class="form-group">
            {{ form.username.label(class="form-control-label") }}
            {%if form.username.errors%}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {%for error in form.username.errors%}
                <span> {{error}} </span>
                  {%endfor%}
                </div>
              {%else%}
              {{form.username (class="form-control form-control-lg") }}
              {%endif%}
            </div>

            <br>
            <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {%if form.email.errors%}
              {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {%for error in form.email.errors%}
                  <span> {{error}}</span>
                  {%endfor%}
                  </div>
                {%else%}
                {{form.email (class="form-control form-control-lg")}}
                {%endif%}
    
              </div>

              <br>
              <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {%if form.password.errors%}
                 {{ form.password(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {%for error in form.password.errors%}
                  <span> {{error}}</span>
                  {%endfor%}
                  </div>
                {%else%}
                {{form.password (class="form-control form-control-lg")}}
                {%endif%}
    
              </div>
              <br>
              <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {%if form.confirm_password.errors%}
                 {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {%for error in form.confirm_password.errors%}
                  <span> {{error}}</span>
                  {%endfor%} 
                  </div>
                {%else%}
                {{form.confirm_password (class="form-control form-control-lg")}}
                {%endif%}
    
              </div>
              <br>
                  <div class="form-group">
                    {{ form.image_file.label() }}
                    <br>
                    {{ form.image_file(class="form-control-file") }}
                    {% if form.image_file.errors %}
                        {%for error in form.image_file.errors%}
                             <span class="text-danger"> {{error}}</span></br>
                        {%endfor%}
                    {%endif%}
                </div>  
              </div>
              <br>
           
        </fieldset>
        <br>
        <div class="form-group">
            {{form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
<br>
  <div class="border-top pt-3">

        <small class="text-muted">
            Besitzen Sie bereits einen Account? <a class= "ml-2" href="/users/login">Login</a>
        </small>
  </div>
  <br>
  <br>
{% endblock body %}

Applikation/flaskr/templates/users/update_account.html
{% extends 'base.html' %}

{%block head  %}
      <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock%}

{%block body  %}
<br>
<h1>PrepPool</h1>
    <br>
    <div class="content-section">
        <div class="media">
        <img class="rounded-circle account-img" style="width:100px;height:100px" src="{{ url_for('static', filename='profile_pics/'+ current_user.image_file) }}">
        
        <div class="media-body">

            <h3 class="account-heading">{{current_user.username}}</h2>
        
            <p class="text_secondary">{{current_user.email}}</p>
        </div>
        </div>

        <div class="content-section">
            <form method="POST" enctype ="multipart/form-data" action="">
                {{ form.hidden_tag() }}
        
                <br>
                <fieldset class="form-group">
                   <legend class="border-bottom mb-4"> Passen Sie Ihr Passwort an </legend>
                                   
                      <br>
                      <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {%if form.password.errors%}
                         {{ form.password(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                        {%for error in form.password.errors%}
                          <span> {{error}}</span>
                          {%endfor%}
                          </div>
                        {%else%}
                        {{form.password (class="form-control form-control-lg")}}
                        {%endif%}
            
                      </div>
                      <br>
                      <div class="form-group">
                        {{ form.confirm_password.label(class="form-control-label") }}
                        {%if form.confirm_password.errors%}
                         {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                        {%for error in form.confirm_password.errors%}
                          <span> {{error}}</span>
                          {%endfor%} 
                          </div>
                        {%else%}
                        {{form.confirm_password (class="form-control form-control-lg")}}
                        {%endif%}
            
                      </div>
                      
                      </div>
                      <br>
                   
                </fieldset>
                
                <div class="form-group">
                    {{form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
        <br>
        <br>
        <div class="content-section">
            <form method="POST" enctype ="multipart/form-data" action="">
                {{ form.hidden_tag() }}
        
                <br>
                <fieldset class="form-group">
                   <legend class="border-bottom mb-4"> Passen Sie Ihr Profilbild an </legend>
                                   
                      <br>
                      
                      
                      <br>
                          <div class="form-group">
                            {{ form.image_file.label() }}
                            <br>
                            {{ form.image_file(class="form-control-file") }}
                            {% if form.image_file.errors %}
                                {%for error in form.image_file.errors%}
                                     <span class="text-danger"> {{error}}</span></br>
                                {%endfor%}
                            {%endif%}
                        </div>  
                      </div>
                      <br>
                   
                </fieldset>
               
                <div class="form-group">
                    {{form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
        <br>
          
          <br>
        {% endblock body %}
        

Applikation/flaskr/templates/users/view_users.html
{% extends 'base.html' %}

{%block head  %}
<title>Nutzer und Nutzerinnen von PrepPool</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock%}

{%block body  %}
<br>
<h1>PrepPool</h1>
    <br>
<div>
<h2 style="display: inline">Nutzer und Nutzerinnen von PrepPool</h2>
<br>
</div>


<br>
<hr>
<table border="0" cellpadding ="5">
 <th>Profilbild</th> 
 <th>Name</th> 
 <th>E-Mail-Adresse</th> 
  {% for user in users%}
<tr>
  <td><img class="rounded-circle account-img" style="width:50px;height:50px" src="{{ url_for('static', filename='profile_pics/'+ user.image_file) }}">
  </td>
  <td>{{ user.username}} </td>
  <td>{{ user.email }} </td>
</tr>
  {%endfor%}
</table>
  



  <br>




{% endblock%}